server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring:
  application:
    name: price-service
  rabbitmq:
    host: rabbitmq
  data:
    mongodb:
      uri: mongodb://mongo:27017/price